### PR TITLE
Start filling out the About page

### LINKED ISSUE #21: Fill in some About page text
The 1.0 version of MolEvolvR has a [help page](https://jravilab.cuanschutz.edu/molevolvr/?r=liasix&p=help) with three tabs and a lot of static content.

Much of this, if not most, is very specific to the design of 1.0, and will thus not be applicable to 2.0. Avoid transferring things that are very layout-specific -- e.g. "go to Advanced Options > Maximum Hits" -- as these may move around or be renamed in 2.0. But there are more general things -- like compatibility, team, links, contact, funding, case studies -- that we can start adding to the 2.0 About page.

### PR DESCRIPTION
**Pull request by Sproff**
Closes #21 

- port over some text from 1.0 help page as appropriate, and make design tweaks and some wording tweaks

### CODE REVIEW

**Comment by Sproff** [comment]
@vincerubinetti kindly take a look at it. 

What's left are the in-depth info and sections for getting sequences. Could you point me to the particular content that needs to be there because the info looks different?

**Comment by Sproff** [comment]
> @vincerubinetti kindly take a look at it.
> 
> What's left are the in-depth info and getting sequences sections. Could you point me to the particular content that needs to be there because the info looks different?

Seems @vincerubinetti is out of reach. Can you check this out so I can wrap up and move on to other issues, please? @jananiravi

**Comment by vincerubinetti** [comment]
I will review it soon, please be patient.

**Comment by Sproff** [comment]
> I will review it soon, please be patient.

Alright, thatnk you.

**Review by vincerubinetti — APPROVED** [review]

**Pull request merged**
